version: '3.8'

services:
  vote:
    image: AcHiLlE006/vote:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  worker:
    image: AcHiLlE006/worker:latest
    depends_on:
      - redis
      - db
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  result:
    image: AcHiLlE006/result:latest
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: "redis:alpine"
    networks:
      - app-network

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "votes"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
