# Fichier docker-compose.yml
version: '3.8'

services:
  vote:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network

  worker:
    build: .
    depends_on:
      - redis
      - db
    networks:
      - app-network

  result:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    networks:
      - app-network

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "votes"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network: